image: docker:18-git

services:
  - docker:18.09-dind

stages:
  - build
 # - deploy
 # - package
 # - release
 # - deploy

variables:
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  # from https://storage.googleapis.com/kubernetes-release/release/stable.txt
  K8S_STABLE_VERSION_URL: https://storage.googleapis.com/kubernetes-release/release/v1.14.1/bin/linux/amd64/kubectl
  DOCKER_TLS_CERTDIR: ""
  PROD_SERVER_IP: zaplog.pro
  PROD_SERVER_USER: owner
  PROD_IMAGE_APP_TAG: registry.gitlab.com/zaplog/api-zaplog:master

build-docker:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "$CI_PROJECT_PATH" | awk -F"/" '{print $2}'
    - docker build -t $CONTAINER_TEST_IMAGE . --build-arg CI_PROJECT_NAME=$CI_PROJECT_PATH
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - master

deploy-to-prod:
  stage: build
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no owner@zaplog.pro "cd ~; touch test.txt"
  only:
    - master
  when: manual
