image: docker:18-git

services:
  - docker:18.09-dind

stages:
  - build
 # - deploy
 # - package
 # - release
 # - deploy

variables:
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  # from https://storage.googleapis.com/kubernetes-release/release/stable.txt
  K8S_STABLE_VERSION_URL: https://storage.googleapis.com/kubernetes-release/release/v1.14.1/bin/linux/amd64/kubectl
  DOCKER_TLS_CERTDIR: ""
  PROD_SERVER_IP: zaplog.pro
  PROD_SERVER_USER: owner
  PROD_IMAGE_APP_TAG: registry.gitlab.com/zaplog/api-zaplog:master

before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

build-docker:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "$CI_PROJECT_PATH" | awk -F"/" '{print $2}'
    - docker build -t $CONTAINER_TEST_IMAGE . --build-arg CI_PROJECT_NAME=$CI_PROJECT_PATH
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - master

deploy-to-prod:
  image: creatiwww/docker-compose
  stage: build
  script:
    - eval $(ssh-agent -s)
    - ssh-add <echo "$SSH_PRIVATE_KEY" | base64 -d
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY_IMAGE
    - echo "EXTERNAL_SERVICE_KEY=$EXTERNAL_SERVICE_PROD_KEY" >> .env
    - echo "IMAGE_APP_TAG=$PROD_IMAGE_APP_TAG" >> .env
    #- docker-compose -H "ssh://$PROD_SERVER_USER@$PROD_SERVER_IP" down --remove-orphans
    - docker-compose -H "ssh://$PROD_SERVER_USER@$PROD_SERVER_IP" pull
    #- docker-compose -H "ssh://$PROD_SERVER_USER@$PROD_SERVER_IP" up -d
  only:
    - master
  when: manual
