USE zaplog;
ALTER TABLE interactions
    ADD FOREIGN KEY (linkid) REFERENCES links (id) ON DELETE CASCADE ON UPDATE CASCADE,
    ADD FOREIGN KEY (channelid) REFERENCES channels (id) ON DELETE CASCADE ON UPDATE CASCADE,
    ADD FOREIGN KEY (reactionid) REFERENCES reactions (id) ON DELETE CASCADE ON UPDATE CASCADE;
